---
scan:
  interval: 60m
  timeout: 5m

discovery:
  kubernetes:
    enabled: true
    source: some-cluster

validations:
  expiry:
    enabled: true
    warning_window: 72h
  tls-version:
    enabled: true
    min_version: 1.3
  trust-chain:
    enabled: false
    ca:
       paths: 
       - /a/ca/path
       - /b/ca/path
       - /c/ca/path

reporters:
  logging:
    enabled: true
  metrics:
    enabled: true