debug: true

scan:
  repeated: true
  interval: 10m
  timeout: 2m

discovery:
  kubernetes:
    source: some-cluster

validations:
  expiry:
    warning_window: 72h
  tls-version:
    min_version: 1.3
  trust-chain:
    ca:
      paths: 
      - /a/ca/path
      - /b/ca/path
      - /c/ca/path