kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "cert-scanner.fullname" . }}
data:
    config.yaml: |
    {{- with .Values.scanConfig }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
  