kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "cert-scanner.fullname" . }}-hosts
data:
    hosts.yaml: |
    {{- with .Values.hosts }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
