---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-scanner.fullname" . }}
  labels:
    {{- include "cert-scanner.labels" . | nindent 4 }}
rules:
- apiGroups: ['']
  resources: [pods]
  verbs: ['list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-scanner.fullname" . }}
  labels:
    {{- include "cert-scanner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-scanner.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "cert-scanner.serviceAccountName" . }}