apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-scanner.fullname" . }}
  labels:
    {{- include "cert-scanner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: metrics
  selector:
    {{- include "cert-scanner.selectorLabels" . | nindent 4 }}
