kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "cert-scanner-canary.fullname" . }}
data:
    config.yaml: |
    {{- with .Values.canaryConfig }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
  