apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-scanner-canary.fullname" . }}
  labels:
    {{- include "cert-scanner-canary.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cert-scanner-canary.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cert-scanner-canary.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: cert-scanner-canary
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "{{ .Values.image.url }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["canary", "-c", "/etc/cert-scanner-canary/config.yaml"]
          ports:
            - name: https
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: cert-scanner-canary-config
              mountPath: /etc/cert-scanner-canary
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: cert-scanner-canary-config
        configMap:
          name: {{ include "cert-scanner-canary.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
