apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-scanner-canary.fullname" . }}
  labels:
    {{- include "cert-scanner-canary.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "cert-scanner-canary.selectorLabels" . | nindent 4 }}
