# Default values for cert-scanner.
replicaCount: 1

scanConfig:
  debug: false

  metrics:
    port: 8080
  
  scan:
    repeated: true
    interval: 1m
    timeout: 1m

  discovery:
    kubernetes:
      source: some-cluster
      ignore:
        - coredns

  validations:
    expiry:
      warning_window: 72h
    tls-version:
      min_version: 1.3
    trust-chain:
      ca:
        paths: 
        - /a/ca/path
        - /b/ca/path
        - /c/ca/path

  reporters:
    logging:
      enabled: true
    metrics:
      enabled: true

image:
  url: docker.io/stevegargan/cert-scanner-darkly
  pullPolicy: IfNotPresent
  tag: 0.0.2

serviceAccount:
  annotations: {}

podSecurityContext: {}

securityContext: 
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  port: 8080

resources: 
  requests:
    cpu: 100m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
