# Default values to install cert-scanner
replicaCount: 1

# port used by the scanner to expose metrics, pprof and probe endpoints.
port: &port 9253

# Scan config yaml templated straight from here into a configMap
# mounted into the scanner container.
scanConfig:
  debug: false

  scan:
    repeated: true
    interval: 1m
    timeout: 1m

  discovery:
    kubernetes:
      source: some-cluster
      ignore:
        - coredns

  validations:
    expiry:
      warning_window: 72h
    tls_version:
      min_version: 1.2
    trust_chain:
      # ca:
      #   paths:
      #   - /a/ca/path
      #   - /b/ca/path
      #   - /c/ca/path

  reporters:
    logging:
      enabled: true

  metrics:
    enabled: true
    port: *port

# use the volumes and mounts to mount any CA bundles your systems use into the scanner
volumes: {}

volumeMounts: {}

image:
  url: docker.io/stevegargan/cert-scanner-darkly
  pullPolicy: IfNotPresent
  tag: 0.0.2

serviceAccount:
  annotations: {}

podSelectorLabels:
  prometheus.io/scrape: 'true'

# recommeded security context is to run as non-root with no
# extra capabiltities.
podSecurityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  port: *port

resources:
  requests:
    cpu: 100m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
