// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import (
	prometheus "github.com/prometheus/client_golang/prometheus"
	mock "github.com/stretchr/testify/mock"
)

// CounterVec is an autogenerated mock type for the CounterVec type
type CounterVec struct {
	mock.Mock
}

// DeleteLabelValues provides a mock function with given fields: lvs
func (_m *CounterVec) DeleteLabelValues(lvs ...string) bool {
	_va := make([]interface{}, len(lvs))
	for _i := range lvs {
		_va[_i] = lvs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 bool
	if rf, ok := ret.Get(0).(func(...string) bool); ok {
		r0 = rf(lvs...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// WithLabelValues provides a mock function with given fields: lvs
func (_m *CounterVec) WithLabelValues(lvs ...string) prometheus.Counter {
	_va := make([]interface{}, len(lvs))
	for _i := range lvs {
		_va[_i] = lvs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 prometheus.Counter
	if rf, ok := ret.Get(0).(func(...string) prometheus.Counter); ok {
		r0 = rf(lvs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(prometheus.Counter)
		}
	}

	return r0
}

// NewCounterVec creates a new instance of CounterVec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCounterVec(t interface {
	mock.TestingT
	Cleanup(func())
}) *CounterVec {
	mock := &CounterVec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
