name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**' 

permissions:
  contents: read
  packages: write 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Push Helm Chart to OCI
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          
          for chartName in "cert-scanner" ; do
            chart = "charts/$chartName"
            if [ -d "$chart" ]; then
              echo "Processing $chart..."
              
              helm package "$chart" --destination .deploy
              PACKAGE=$(ls .deploy/*.tgz | head -n 1)
              helm push "$PACKAGE" oci://ghcr.io/$OWNER/charts
              rm -rf .deploy
            fi
          done